### ISSUE TITLE
[Chapter 18] Error in TF-Agents environment with the env.step() function

### ISSUE THREAD

**Issue by Quaniful** [ageron/handson-ml2#307]
Hi,

I am getting an error here in chapter 18 after importing TF-Agents, creating an environment and trying to take a step.

```
from tf_agents.environments import suite_gym
env = suite_gym.load('Breakout-v4')
env.reset()
env.step(1)
```

This generates an AttributeError:
`AttributeError: 'int' object has no attribute 'item'`

It's stated in the documentation that this environment has 4 discrete actions.

It seems to work when I use a NumPy array with one integer from 0 to 3 in it like this:
`env.step(np.array([1]))`

It seems like this error arises from here:

```
~/Desktop/Python/ml/ml_venv/lib/python3.8/site-packages/tf_agents/environments/gym_wrapper.py in _step(self, action)
    210     # actions we have a numpy scalar (e.g array(2)) which is not hashable
    211     # in this case, we simply pull out the scalar value which will be hashable.
--> 212     action = action.item() if self._action_is_discrete else action
```

**Comment by C6H6Cl6** [comment]
I found this error either and fixed it by using the format u mentioned

**Comment by ageron** [comment]
Thanks for your feedback. Indeed, this seems to be a bug in TF Agents, which was apparently introduced in version 0.4.0. The same code used to work fine in version 0.3.0. I filed [issue #520](https://github.com/tensorflow/agents/issues/520) for TF Agents. I'll keep this issue open until the TF Agents issue is resolved, but please refer to this other issue.

In the meantime, one workaround is simply to use `env.step(np.array(1))` instead of `env.step(1)`.

Hope this helps.

**Comment by Quaniful** [comment]
I think I understood where this bug is coming from, in a gym environment there is an option to run episodes in parallel (in a vectorized fashion), that is why the environment expects an array of actions, if there is 1 copy of an environment then an array of length 1 will satisfy.

**Comment by ageron** [comment]
The TF Agents issue was resolved, and I've updated this project to use the latest version of TF Agents, so `env.step(1)` now works fine. 😊 
Closing this issue.
